### ISSUE TITLE
We Detected An Unusual Login Attempt

### ISSUE THREAD

**Issue by nbgabriel** [instabot-py/instabot.py#1551]
Hello there!
Exists some workaround to avoid this message "We Detected An Unusual Login Attempt" ? 

The instabot.py shows me "INFO:Login error! Connection error!"

Days ago, changing the password does the trick, but is not working now. Any Ideas? 

Thanks

**Comment by nbgabriel** [comment]
I fix it following this post:
https://github.com/instabot-py/instabot.py/issues/1287#issuecomment-391149245

**Comment by datarhan** [comment]
@nbgabriel what branch? Could you leave a link, please?

**Comment by nbgabriel** [comment]
@datarhan sure, this is the link https://github.com/erikpi/instabot.py

BUT!!!!!!!! is not working anymore. I dont understand instagram. I try all solutions that people recommend in previuos post, but nothing. I think that is some security from instagram, something random, try it, maybe its your lucky day. 

If someelse, has any solution, please comment it.

**Comment by datarhan** [comment]
@nbgabriel, tnx! but it didn't help.

**Comment by Zethrus** [comment]
I am also having this issue :(
Although, I am running from a VPS which is most likely why, huh?

**Comment by Zethrus** [comment]
Fixed with this fork: https://github.com/erikpi/instabot.py

**Comment by LopesX** [comment]
did not work

**Comment by nimrodazoulai** [comment]
Hi guys, I think the solution [here](https://github.com/instabot-py/instabot.py/issues/1581) can work for you too.

**Comment by loganyc1934** [comment]
The above solution didn't work for me. Used hardcoded user agent and still getting blocked by " Unusual Login Attempt"

**Comment by DubDubDan** [comment]
A serious solution for this would be to use the python script in a bare linux cloud based hosted server(I use cloud.google.com). And as I move around, I need to move the location of the hosted server. This works well for me, as instagram will probably assume that you cannot be logged on at two locations at once. Long winded - I know. But it _does_ work.

**Comment by LopesX** [comment]
It's Work: https://github.com/instabot-py/instabot.py/issues/1581#issuecomment-420540153

**Comment by LopesX** [comment]
@nbgabriel If works fine, please close the Issue

**Comment by nbgabriel** [comment]
Awesome LopesX!!!!!!

Thanks a lot! Its working now!
