### ISSUE TITLE
Instaloader and crftoken fix - login error connection error

### ISSUE THREAD

**Issue by sannyd** [instabot-py/instabot.py#1787]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [X] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

Applied both fixes as of the last couple of days, but now it seems to be not allowing me to log in without any verification or suspicious activity on the IG website.  Anyone have any ideas?

**Comment by sannyd** [comment]
just to clarify further, I also tried replacing the user agent, which has worked in the past.

**Comment by nachovoss** [comment]
did you try?[https://github.com/instabot-py/instabot.py/pull/1775](url)

**Comment by sannyd** [comment]
> did you try?[https://github.com/instabot-py/instabot.py/pull/1775](url)

yes @nachovoss I did.  Thank you for the reply.

**Comment by yepnode** [comment]
Same error here.

**Comment by jyetrudinger** [comment]
Same here - I've tried every fix offered in other threads - nothing seems to fix it

**Comment by vineeth-pradhan** [comment]
I faced the same issue today but I followed these steps and this fixed it:

1. Run the script and it fails with above error
2. Open Instagram on your device and you'd most probably see a screen to confirm if it was you who tried to login earlier from an unrecognised source. Select "Yes, this was me"
3. Run the script again and this should work now. Let me know if this solves the problem

I suppose Instagram has come up with a feature to address cyber security issues and one of them is to prohibit the bots from proxying. For this reason you'd probably be logged out automatically due to avoid "somebody else" trying to login from an unauthorised source

**Comment by jyetrudinger** [comment]
> I faced the same issue today but I followed these steps and this fixed it:
> 
> 1. Run the script and it fails with above error
> 2. Open Instagram on your device and you'd most probably see a screen to confirm if it was you who tried to login earlier from an unrecognised source. Select "Yes, this was me"
> 3. Run the script again and this should work now. Let me know if this solves the problem
> 
> I suppose Instagram has come up with a feature to address cyber security issues and one of them is to prohibit the bots from proxying. For this reason you'd probably be logged out automatically to avoid "somebody else" trying to login from an unauthorised source

I've tried this several times and no luck :/

**Comment by Daimonion1980** [comment]
i had to start over after getting csrftoken error. i cloned the repo again, pulled my changes to it and applied https://github.com/instabot-py/instabot.py/pull/1775
After this my bot worked flawlessly. 

So, you didn't provide any complete errormessage. Can you post it?

**Comment by marcosenno88** [comment]
seme here

**Comment by fab976** [comment]
Same for me, also treid every Fix I could find including #1775 but nothing helped.
Still getting Login Error (And no, instagram doesn`t show me some "was it you" in the App :/)

**Comment by steffo93** [comment]
Same here.

**Comment by Daimonion1980** [comment]
Please provide an appropriate error message or an traceback! Otherwise nobody can help you!

**Comment by sannyd** [comment]
> Please provide an appropriate error message or an traceback! Otherwise nobody can help you!

10.12.2018_16:35 Login error! Connection error!
10.12.2018_16:35 Removing already liked medias..
10.12.2018_16:35 Trying to unfollow #1: 
10.12.2018_16:35 Looks like there is nobody to unfollow.
10.12.2018_16:36 Removing already liked medias..
10.12.2018_16:36 Removing already liked medias..

**Comment by newielander** [comment]
After applying the changes in #1755 I now get this error:

```
C:\Users\Tim\Downloads\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\Tim\Downloads\instabot.py-master\src\__init__.py", line 1, in <
module>
    from .instabot import InstaBot
  File "C:\Users\Tim\Downloads\instabot.py-master\src\instabot.py", line 19, in
<module>
    from .sql_updates import check_already_followed, check_already_unfollowed
ImportError: cannot import name 'check_already_unfollowed'
```

**Comment by Nuggedo** [comment]
Hello there, after aplying the changes wich fixed problem with loop, it worked until today morning. and after that i got next error below. I reinstall everything what i should, but still, the same problem. any solutions? 
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 97, in get_browsers
    html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 45, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/mikehunt/Public/instabot.py-master-UU/src/instabot.py", line 168, in __init__
    fake_ua = UserAgent()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached`

**Comment by Daimonion1980** [comment]
@newielander it seems that your follows_db.db has no sql table check_already_unfollowed.
So, try to rename the follows_db.db and let instabot generate a new one. (Yep the data collected till now will be lost, but in my case i dont't have any important data.)

@Nuggedo it seems that this is a general python error: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

@sannyd maybe a clean src folder (copy from master branch) can help you to get the connection error fixed

In my case i had to clone the whole src folder and patch https://github.com/instabot-py/instabot.py/pull/1775 before the bot started to working again.

**Comment by Nuggedo** [comment]
> @newielander it seems that your follows_db.db has no sql table check_already_unfollowed.
> So, try to rename the follows_db.db and let instabot generate a new one. (Yep the data collected till now will be lost, but in my case i dont't have any important data.)
> 
> @Nuggedo it seems that this is a general python error: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
> 
> @sannyd maybe a clean src folder (copy from master branch) can help you to get the connection error fixed
> 
> In my case i had to clone the whole src folder and patch #1775 before the bot started to working again.
in the end, i really dont understand what i should do .. i did nothing, and now i must do something about i have realy no clue

**Comment by newielander** [comment]
> 
> 
> @newielander it seems that your follows_db.db has no sql table check_already_unfollowed.
> So, try to rename the follows_db.db and let instabot generate a new one. (Yep the data collected till now will be lost, but in my case i dont't have any important data.)
> 
> @Nuggedo it seems that this is a general python error: https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
> 
> @sannyd maybe a clean src folder (copy from master branch) can help you to get the connection error fixed
> 
> In my case i had to clone the whole src folder and patch #1775 before the bot started to working again.

Hi there, I just tried what you did and I am getting the same exact error, thanks anyways for trying to help me!

**Comment by blackfactory** [comment]
Traceback (most recent call last):
File "example.py", line 52, in 
unfollow_whitelist=['example_user_1', 'example_user_2'])
File "/Users/iclons3/Desktop/botb/src/instabot.py", line 167, in init
fake_ua = UserAgent()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/fake.py", line 69, in init
self.load()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/fake.py", line 78, in load
verify_ssl=self.verify_ssl,
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 245, in update
write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 189, in load
verify_ssl=verify_ssl,
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 84, in get
raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

Can anyone help pleaseee??? :(
