### ISSUE TITLE
disable "Removing already liked medias"

### ISSUE THREAD

**Issue by Koldrish** [instabot-py/instabot.py#999]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
 Windows

## Python Version?
3

## Description
Can I disable "Removing already liked medias"? 
I prefer that skip without removing "like"

**Comment by oidevelop** [comment]
I solved with a comment on raw 693 of the file instabot.py (#self.remove_already_liked ())

**Comment by brunomosciatti** [comment]
Now I cant login:


28.02.2018_10:58 Trying to login as myusername...

28.02.2018_10:58 Login error! Check your login data!
28.02.2018_10:58 Trying to unfollow #1: 

the pw is correct and i've already tried to change it and still the same error

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by techchannnelandtutorials** [comment]
Lol just found soloution to the login error shit. Go to instabot.py line 65 where you will replace the self useragent with your browser's useragent. First login to chrome for an example to your instagram, next head over to https://developers.whatismybrowser.com/useragents/explore click on search which will find your useragent.
